config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'lessons/schedule', to: 'lessons#schedule'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end

  def new
    @user= User.new
  end

  def create
    @user=User.create(params.require(:user).permit(:title,:name,:start,:end))
    if @user.save
      flash[:notice]="スケジュールを新規登録しました"
      redirect_to :users
    else
      render "new"
    end
  end

  def show
    @user=User.find(params[:id])
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update(params.require(:user).permit(:title,:name,:start,:end))
      flash[:notice]="スケジュールを変更しました"
      redirect_to :users
    else
      render "edit"
    end
  end

  def destroy
    @user=User.find(params[:id])
    @user.destroy
    flash[:notice]
    redirect_to :users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <<header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h3>スケジュール編集</h3>

<%= form_for @user do |f| %>
  <table>
    <tr>
      <th><%= f.label :title,"タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <th><%= f.label :start,"開始日" %></th>
      <td><%= f.date_field :start %></td>
    </tr>
    <tr>
      <th><%= f.label :end,"終了日" %></th>
      <td><%= f.date_field :end %></td>
    </tr>
    <tr>
      <th><%= f.label :note,"スケジュールメモ" %></th>
      <td><%= f.text_area :name %></td>
    </tr>
  </table>
  <ul>
    <li><%= f.submit "スケジュールの編集完了" %></li>
    <li><%= link_to "スケジュール一覧", :users %></li>
  </ul>
<% end %>

app/views/users/index.html.erb
<div class="main">
  <h3>スケジュール一覧</h3>

  <% if flash.notice %>
  <p class="notice"><%= flash.notice %></p>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>タイトル</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>スケジュール更新日時</th>
        <th>確認</th>
        <th>編集</th>
        <th>削除</th>
      </tr>
      <thead>
      <tbody>
        <%@users.each do |user|%>
          <tr>
            <td><%=user.id%></td>
            <td><%=user.title%></td>
            <td><%=user.start.strftime('%Y年%m月%d日')%></td>
            <td><%=user.end.strftime('%Y年%m月%d日')%></td>
            <td><%=user.updated_at.to_s(:datetime_jp)%></td>
            <td><%= link_to "確認" , user %></td>
            <td><%= link_to "編集" , [:edit,user] %></td>
            <td><%= link_to "削除", user, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
          </tr>
          <%end%>
      </tbody>
    </table>
    <p><%= link_to "スケジュール新規登録", new_user_path %></p>
</div>

<footer>
  <h3>現在の日付 :<%= Date.current.strftime('%Y年%m月%d日') %></h3>
  <h3 class="schedule_total">スケジュール合計数 :<%= User.count %></h3>
</footer>

app/views/users/new.html.erb
<h3>スケジュール新規作成</h3>

<%= form_for @user do |f| %>
 <table>
   <tr>
     <th><%= f.label :title,"タイトル" %></th>
     <td><%= f.text_field :title %></td>
   </tr>
   <tr>
     <th><%= f.label :start,"開始日" %></th>
     <td><%= f.date_field :start %></td>
   </tr>
   <tr>
     <th><%= f.label :end,"終了日" %></th>
     <td><%= f.date_field :end %></td>
   </tr>
   <tr>
     <th><%= f.label :note,"スケジュールメモ" %></th>
     <td><%= f.text_area :name %></td>
   </tr>
 </table>
 <ul>
   <ul>
     <li><%= f.submit "スケジュールを新規登録する" %></li>
     <li><%= link_to "スケジュール一覧に戻る",:users %></li>
   </ul>
 </ul>
<% end %>

app/views/users/show.html.erb
<h3>スケジュール詳細</h3>

<table>
  <tr>
    <th>タイトル</th>
    <td><%= @user.title %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @user.start.strftime('%Y年%m月%d日') %></td>
  </tr>
  <tr>
    <th>更新日</th>
    <td><%= @user.updated_at.to_s(:datetime_jp) %></td>
  </tr>
  <tr>
    <th>スケジュールメモ</th>
    <td><%= @user.name %></td>
  </tr>
</table>

<div>
  <ul>
    <li><%= link_to "スケジュール一覧に戻る", :users %></li>
    <li><%= link_to "スケジュールを編集する", edit_user_path %></li>
    <li><%= link_to "スケジュールを削除する", user_path, method: :delete, data: { confirm: "本当に削除しますか？" } %></li>
  </ul>
</div>